import { StyleSheet } from 'react-native';
import { Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: Spacing.four,
  },
  centerSpinner: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.four,
    paddingVertical: Spacing.three,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.two,
    paddingHorizontal: Spacing.four,
    borderRadius: 99,
    gap: Spacing.one,
  },
  addBtnText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
  },
  filterRow: {
    flexDirection: 'row',
    paddingHorizontal: Spacing.four,
    marginBottom: Spacing.three,
    gap: Spacing.two,
  },
  filterPill: {
    paddingVertical: Spacing.one,
    paddingHorizontal: Spacing.three,
    borderRadius: 99,
  },
  filterPillText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 12,
    fontWeight: '600',
  },
  heatmapSection: {
    marginBottom: Spacing.five,
  },
  heatmapRowContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  dayLabelsColumn: {
    paddingLeft: Spacing.two,
    paddingTop: 22,
    gap: 4,
  },
  dayLabel: {
    fontFamily: 'Pliant-Bold',
    fontSize: 9,
    height: 18,
    lineHeight: 18,
    textAlign: 'center',
    width: 12,
  },
  gridScroll: {
    paddingVertical: Spacing.one,
  },
  gridColumnsContainer: {
    flexDirection: 'row',
    gap: 4,
  },
  gridColumn: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  monthHeaderContainer: {
    height: 18,
    justifyContent: 'center',
    alignSelf: 'flex-start',
    marginBottom: Spacing.one,
  },
  monthLabel: {
    fontFamily: 'Pliant-Bold',
    fontSize: 10,
    fontWeight: '700',
  },
  cellsColumn: {
    gap: 4,
  },
  gridCell: {
    width: 18,
    height: 18,
    borderRadius: 3.5,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
    marginTop: Spacing.three,
  },
  gridCellLegend: {
    width: 12,
    height: 12,
    borderRadius: 2,
  },
  legendText: {
    fontSize: 12,
    marginHorizontal: Spacing.one,
  },
  metricsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Spacing.three,
    borderRadius: Spacing.three,
    marginBottom: Spacing.five,
  },
  metricSection: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricDivider: {
    width: 1,
    height: 24,
    opacity: 0.15,
  },
  timelineSection: {
    gap: Spacing.three,
  },
  timelineTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: Spacing.two,
  },
  timelineHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.two,
  },
  timelineHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.one,
  },
  timelineTitleNew: {
    fontFamily: 'Pliant-Bold',
    fontSize: 11,
    letterSpacing: 1.5,
  },
  timelineCountBadge: {
    paddingHorizontal: Spacing.two,
    paddingVertical: 3,
    borderRadius: 12,
  },
  timelineCountText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 10,
  },
  cardHeaderNew: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.two,
  },
  cardHeaderLeftNew: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
    marginRight: Spacing.two,
  },
  beltDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  partnerNameText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 14,
    flexShrink: 1,
  },
  cardDateNew: {
    fontFamily: 'Pliant-Regular',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  badgesWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: Spacing.three,
  },
  miniChip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  miniChipText: {
    fontFamily: 'Pliant-Regular',
    fontSize: 11,
  },
  focusContainerNew: {
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.two,
    borderRadius: 8,
    marginBottom: Spacing.two,
  },
  focusLabelNew: {
    fontFamily: 'Pliant-Bold',
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  focusValueNew: {
    fontFamily: 'Pliant-Regular',
    fontSize: 13,
    lineHeight: 18,
  },
  emptyCard: {
    padding: Spacing.six,
    borderRadius: Spacing.four,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineItem: {
    flexDirection: 'row',
  },
  timelineLeftColumn: {
    width: 32,
    alignItems: 'center',
  },
  timelineNode: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 3.5,
    backgroundColor: 'transparent',
    marginTop: 20,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    marginTop: 4,
    marginBottom: -20,
  },
  timelineCard: {
    flex: 1,
    padding: Spacing.five,
    borderRadius: 16,
    marginBottom: Spacing.four,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.one,
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  tag: {
    fontFamily: 'Pliant-Regular',
    fontSize: 11,
    fontWeight: '600',
    paddingHorizontal: Spacing.two,
    paddingVertical: 2,
    borderRadius: 99,
  },
  cardDate: {
    fontSize: 11,
    textTransform: 'uppercase',
  },
  metaBadgeRow: {
    flexDirection: 'row',
    gap: Spacing.three,
    marginBottom: Spacing.three,
  },
  badgeText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 11,
  },
  focusText: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: Spacing.three,
  },
  spaciousChainContainer: {
    marginVertical: Spacing.three,
    gap: Spacing.three,
  },
  spaciousChainCard: {
    borderRadius: 12,
    padding: Spacing.four,
  },
  spaciousChainContent: {
    flex: 1,
  },
  chainTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: Spacing.two,
  },
  miniTag: {
    paddingHorizontal: Spacing.two,
    paddingVertical: 2,
    borderRadius: 4,
  },
  miniTagText: {
    fontFamily: 'Pliant-Regular',
    fontSize: 10,
  },
  chainMemoText: {
    fontFamily: 'Pliant-Regular',
    fontSize: 12,
    fontStyle: 'italic',
    marginTop: Spacing.two,
  },
  lockerMemoBox: {
    padding: Spacing.three,
    borderRadius: Spacing.three,
    marginTop: Spacing.two,
  },
  bottomSheetHeaderNew: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.four,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
    paddingBottom: Spacing.three,
  },
  bottomSheetTitleNew: {
    fontFamily: 'Pliant-Bold',
    fontSize: 16,
  },
  bottomSheetSubtitleNew: {
    fontFamily: 'Pliant-Regular',
    fontSize: 11,
    marginTop: 2,
  },
  closeBtnNew: {
    padding: 6,
    borderRadius: 8,
  },
  metaMetricsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: Spacing.four,
  },
  miniMetricCard: {
    flex: 1,
    padding: Spacing.four,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniMetricLabel: {
    fontFamily: 'Pliant-Bold',
    fontSize: 9,
    letterSpacing: 1,
    marginBottom: 4,
  },
  miniMetricVal: {
    fontFamily: 'Pliant-Bold',
    fontSize: 13,
  },
  intensityDots: {
    fontFamily: 'Pliant-Bold',
    fontSize: 12,
    marginTop: 4,
    letterSpacing: 2,
  },
  feelScoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    gap: 4,
  },
  feelScoreBadge: {
    borderWidth: 1.5,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  feelScoreText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 13,
  },
  feelScoreMax: {
    fontFamily: 'Pliant-Regular',
    fontSize: 10,
  },
  detailFocusBox: {
    padding: Spacing.four,
    borderRadius: 16,
    marginBottom: Spacing.four,
  },
  detailMetaLabel: {
    fontFamily: 'Pliant-Bold',
    fontSize: 9,
    letterSpacing: 1,
    marginBottom: 4,
  },
  shareRoundButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
  },
  shareRoundButtonText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 12,
  },
  graphContainer: {
    padding: Spacing.five,
    borderRadius: 20,
    alignItems: 'center',
    marginBottom: Spacing.two,
  },
  graphTitle: {
    fontFamily: 'Pliant-Bold',
    fontSize: 10,
    letterSpacing: 1.5,
    marginBottom: Spacing.four,
  },
  graphNodePosition: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 99,
    minWidth: 200,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  graphNodeSubmission: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 99,
    minWidth: 200,
    justifyContent: 'center',
    borderWidth: 1,
  },
  graphNodeText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 12,
  },
  graphEdgeContainer: {
    alignItems: 'center',
    width: '100%',
  },
  graphEdgeLine: {
    width: 1.5,
    height: 14,
  },
  graphMoveChip: {
    borderWidth: 1,
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: 'center',
    marginVertical: 2,
    minWidth: 160,
  },
  graphMoveActor: {
    fontFamily: 'Pliant-Bold',
    fontSize: 9,
    letterSpacing: 0.5,
  },
  graphMoveAction: {
    fontFamily: 'Pliant-Regular',
    fontSize: 11,
    marginTop: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalOverlayFullScreen: {
    flex: 1,
  },
  modalContentFullScreen: {
    flex: 1,
    paddingHorizontal: Spacing.five,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.three,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
  },
  modalTitleFullScreen: {
    fontFamily: 'Pliant-Bold',
    fontSize: 24,
    fontWeight: '700',
  },
  breadcrumbText: {
    fontFamily: 'Pliant-Regular',
    fontSize: 12,
    marginTop: 2,
  },
  stepIndicatorRow: {
    flexDirection: 'row',
    height: 3,
    gap: 6,
    marginBottom: Spacing.four,
    paddingHorizontal: Spacing.one,
  },
  stepIndicatorLine: {
    flex: 1,
    height: 3,
    borderRadius: 9,
  },
  closeBtn: {
    padding: Spacing.one,
  },
  modalForm: {
    paddingBottom: Spacing.six,
  },
  stepContainer: {
    paddingVertical: Spacing.one,
  },
  formSectionHeader: {
    marginBottom: Spacing.three,
  },
  formSectionTitle: {
    fontFamily: 'Pliant-Bold',
    fontSize: 16,
    fontWeight: '700',
  },
  divider: {
    height: 1.5,
    backgroundColor: 'rgba(0,0,0,0.06)',
    marginVertical: Spacing.four,
  },
  formGroup: {
    marginBottom: Spacing.four,
  },
  formSubGroup: {
    marginBottom: Spacing.three,
  },
  label: {
    marginBottom: Spacing.two,
  },
  fieldLabelMinimal: {
    fontFamily: 'Pliant-Regular',
    fontSize: 13,
    marginBottom: Spacing.one,
  },
  subLabel: {
    marginBottom: Spacing.one,
    fontSize: 12,
  },
  input: {
    fontFamily: 'Pliant-Regular',
    borderRadius: Spacing.three,
    paddingVertical: Spacing.three,
    paddingHorizontal: Spacing.three,
    fontSize: 15,
    borderWidth: 0,
  },
  inputMini: {
    fontFamily: 'Pliant-Regular',
    borderRadius: Spacing.two,
    paddingVertical: Spacing.two,
    paddingHorizontal: Spacing.two,
    fontSize: 13,
    borderWidth: 0,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  btnRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.two,
  },
  selectorBtnText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 12,
    fontWeight: '600',
  },
  builderChainSpacious: {
    marginVertical: Spacing.two,
    gap: Spacing.four,
  },
  spaciousBuilderCard: {
    borderRadius: 16,
    padding: Spacing.five,
  },
  builderCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.three,
  },
  builderCardTitle: {
    fontFamily: 'Pliant-Bold',
    fontSize: 14,
    fontWeight: '700',
  },
  pillListWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginVertical: Spacing.one,
  },
  actionOptionPill: {
    borderRadius: 8,
    paddingVertical: Spacing.two,
    paddingHorizontal: Spacing.three,
  },
  actionOptionPillText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 12,
  },
  horizontalScroll: {
    paddingVertical: Spacing.one,
  },
  horizontalPill: {
    borderRadius: 8,
    paddingVertical: Spacing.two,
    paddingHorizontal: Spacing.three,
  },
  microNotesToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: Spacing.two,
    marginTop: Spacing.two,
    borderTopWidth: 1,
  },
  microNotesDrawer: {
    marginTop: Spacing.two,
    gap: Spacing.two,
  },
  microNotesSectionTitle: {
    fontSize: 11,
    textTransform: 'uppercase',
  },
  quickTagsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginVertical: Spacing.one,
  },
  quickTagBtn: {
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  quickTagText: {
    fontFamily: 'Pliant-Regular',
    fontSize: 12,
  },
  addEventBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderRadius: Spacing.three,
    paddingVertical: Spacing.three,
    marginVertical: Spacing.two,
    gap: Spacing.one,
  },
  addEventBtnText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 13,
    fontWeight: '700',
  },
  feelRatingRow: {
    flexDirection: 'row',
    gap: Spacing.three,
    justifyContent: 'space-between',
  },
  feelRatingDot: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navRow: {
    flexDirection: 'row',
    gap: Spacing.three,
    marginTop: Spacing.four,
  },
  navBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Spacing.three,
    paddingVertical: Spacing.three,
    paddingHorizontal: Spacing.four,
    gap: Spacing.one,
    height: 48,
  },
  navBtnText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 14,
    fontWeight: '700',
  },
  submitBtn: {
    borderRadius: Spacing.three,
    alignItems: 'center',
    justifyContent: 'center',
    height: 48,
  },
  submitBtnText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 15,
    fontWeight: '700',
    color: '#ffffff',
  },
  popoverCard: {
    margin: Spacing.five,
    borderRadius: Spacing.four,
    padding: Spacing.five,
    alignSelf: 'stretch',
  },
  createPartnerSubCard: {
    borderRadius: 16,
    padding: Spacing.five,
    marginBottom: Spacing.four,
  },
  partnerDetailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
    marginBottom: Spacing.four,
    paddingHorizontal: Spacing.one
  },
  durationRow: {
    flexDirection: 'row',
    gap: Spacing.three
  },
  bottomSheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  bottomSheetBackdrop: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  bottomSheetContent: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: Spacing.five,
    maxHeight: '60%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
  },
  bottomSheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.four,
    paddingBottom: Spacing.two,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(0,0,0,0.06)',
  },
  bottomSheetTitle: {
    fontFamily: 'Pliant-Bold',
    fontSize: 16,
    fontWeight: '700',
  },
  tokenPill: {
    borderRadius: 6,
    paddingVertical: 3,
    paddingHorizontal: 8,
    marginHorizontal: 4,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tokenText: {
    fontFamily: 'Pliant-Bold',
    fontSize: 14,
    color: '#E63462',
  }
});
